<div style="background: linear-gradient(120deg, #1a3a5c 0%, #2d6a9f 60%, #4a9eda 100%); padding: 28px 36px; border-radius: 14px; display: flex; align-items: center; gap: 28px; box-shadow: 0 4px 18px rgba(0,0,0,0.18);">
    <img src='Figures/iteso.jpg' style="height: 110px; border-radius: 8px; background: white; padding: 6px; flex-shrink: 0; box-shadow: 0 2px 8px rgba(0,0,0,0.2);"/>
    <div style="border-left: 2px solid rgba(255,255,255,0.4); padding-left: 28px;">
        <h1 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Ingeniería y Ciencia de Datos</h1>
        <h3 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Laboratorio de Procesamiento de Datos</h3>
        <h3 style="margin: 0; color: rgba(255,255,255,0.8); font-weight: normal; font-size: 1.05em;">Módulo 1: Extracción de datos de diferentes fuentes: Archivos XML</h3>
    </div>
</div>

# Archivos XML

XML organiza la información como un árbol de elementos. Cada nodo puede tener una etiqueta, atributos, texto y nodos hijos. Esta jerarquía permite representar relaciones complejas, aunque requiere recorrer el árbol para llegar a los valores.

En los ejemplos se usan dos enfoques: `find`/`findall` para rutas conocidas y recorridos anidados cuando se necesita explorar la estructura. Al convertir XML a tabla hay que decidir qué nodo representa una fila y cómo tratar los elementos que faltan o se repiten.

El formato XML es común para el intercambio de datos estructurados. Python ofrece la librería estándar `xml.etree.ElementTree` para analizar y extraer información de archivos XML.

In [1]:
# Configuración común para ejecutar esta sección de forma independiente
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dir_base = os.getcwd()
print(dir_base)
ruta = os.path.join(dir_base, 'Data')
print(ruta)

C:\Users\uie70742\OneDrive - ITESO\ITESO\Ingeniería y Ciencia de Datos\Laboratorio_de_Procesamiento_de_Datos_02026\Modulo I
C:\Users\uie70742\OneDrive - ITESO\ITESO\Ingeniería y Ciencia de Datos\Laboratorio_de_Procesamiento_de_Datos_02026\Modulo I\Data

In [2]:
import xml.etree.ElementTree as ET

In [3]:
xml_data = '''
<personas>
  <persona>
    <nombre>Ana</nombre>
    <edad>23</edad>
  </persona>
  <persona>
    <nombre>Luis</nombre>
    <edad>31</edad>
  </persona>
</personas>
'''

In [4]:
root = ET.fromstring(xml_data)
print('Personas extraídas del archivo XML:')
for persona in root.findall('persona'):
    nombre = persona.find('nombre').text
    edad = persona.find('edad').text
    print(f'Nombre: {nombre}, Edad: {edad}')

Personas extraídas del archivo XML:
Nombre: Ana, Edad: 23
Nombre: Luis, Edad: 31

### Anatomía de un documento XML

Un XML es un **árbol**: todo cuelga de un único elemento raíz. Cada **nodo** puede tener:

- una **etiqueta** (`tag`), p. ej. `<country>`;
- **atributos** (`attrib`), p. ej. `name="Singapore"`;
- **texto** (`text`), p. ej. `<rank>4</rank>`;
- **nodos hijos** anidados.

```mermaid
flowchart LR
    D["data (raíz)"] --> C1["country name='Liechtenstein'"]
    D --> C2["country name='Singapore'"]
    C1 --> R1["rank: 1"]
    C1 --> Y1["year: 2008"]
    C1 --> G1["gdppc: 141100"]
```

Con `xml.etree.ElementTree` recorremos ese árbol a mano; pero pandas ofrece además un atajo muy potente: `pd.read_xml`.

#### Métodos clave para navegar el árbol

| Método / atributo | Qué hace |
|---|---|
| `getroot()` | devuelve el nodo raíz |
| `nodo.tag` | nombre de la etiqueta |
| `nodo.attrib` | diccionario de atributos |
| `nodo.text` | texto contenido |
| `nodo.find('hijo')` | primer hijo que coincide |
| `nodo.findall('hijo')` | lista de hijos que coinciden |
| `nodo.iter('tag')` | recorre todos los descendientes con esa etiqueta, sin importar el nivel |

In [5]:
# Patrón muy común: recorrer el árbol y construir una lista de diccionarios
arbol = ET.parse(ruta + '/tabla_1.xml')
raiz = arbol.getroot()

In [6]:
raiz

In [7]:
#inspeccionar los datos del archivo xml
for nodo in raiz:
    print(nodo.attrib,nodo.text,nodo.tag)
    for sn in nodo:
        print(sn.attrib,sn.text,sn.tag)

{'name': 'Liechtenstein'}
         country
{} 1 rank
{} 2008 year
{} 141100 gdppc
{'name': 'Singapore'}
         country
{} 4 rank
{} 2011 year
{} 59900 gdppc
{'name': 'Panama'}
         country
{} 68 rank
{} 2011 year
{} 13600 gdppc

In [8]:
#Extraer los datos de tabla_1.xml
d={}
for nodo in raiz:
    d[nodo.tag]=[]
for nodo in raiz:
    d[nodo.tag].append(nodo.attrib['name'])
for nodo in raiz:
    for sn in nodo:
        d[sn.tag]=[]
for nodo in raiz:
    for sn in nodo:
        d[sn.tag].append(sn.text)
d

{'country': ['Liechtenstein', 'Singapore', 'Panama'],
 'rank': ['1', '4', '68'],
 'year': ['2008', '2011', '2011'],
 'gdppc': ['141100', '59900', '13600']}

In [9]:
pd.DataFrame(d)

         country rank  year   gdppc
0  Liechtenstein    1  2008  141100
1      Singapore    4  2011   59900
2         Panama   68  2011   13600

In [10]:
registros = []
for pais in raiz.findall('country'):
    registros.append({
        'pais': pais.attrib['name'],          # atributo del nodo
        'rank': int(pais.find('rank').text),  # texto de un hijo
        'year': int(pais.find('year').text),
        'gdppc': int(pais.find('gdppc').text)
    })

df_paises_xml = pd.DataFrame(registros)
df_paises_xml

            pais  rank  year   gdppc
0  Liechtenstein     1  2008  141100
1      Singapore     4  2011   59900
2         Panama    68  2011   13600

##### Ejemplo con tabla_2.xml

In [11]:
archivo_2=ET.parse(ruta+'/tabla_2.xml')
root=archivo_2.getroot()
for nodo in root:
    print(nodo.tag,nodo.attrib,nodo.text)

documents {'count': 'N'}

In [12]:
for nodo in root:
    for subn in nodo:
        print(subn.tag,subn.attrib,subn.text)

document {'KEY': 'e95a9a6c790ecb95e46cf15bee517651', 'web': 'www.ubm/doc004.com'} Nevertheless, high and based on experience, fluctuating throughput levels contradict high reliability.


document {'KEY': 'bc360cfbafc39970587547215162f0db', 'web': 'www.ubm/doc006.com'} As long as the production is not conducted on the basis of concrete customer orders, the companies objectives


document {'KEY': '19e71144c50a8b9160b3f0955e906fce', 'web': 'www.ubm/doc005.com'} Many companies today, in different fields of operations and sizes, have access to a vast amount of data which was not available only a couple of years ago.


document {'KEY': '21d4af9021a174f61b884606c74d9e42', 'web': 'www.ubm/doc002.com'} A famous example of a successful prediction is by the German astronomer Johann Gottfried Galle


document {'KEY': '28a45eb2460899763d709ca00ddbb665', 'web': 'www.ubm/doc001.com'} A more recent example of the same kind is the prediction of the Higgs boson by Francois Englert and Peter Higgs

In [13]:
archivo=ET.parse(ruta+'/tabla_2.xml')
raiz=archivo.getroot()

In [14]:
L=[]
for n in raiz.findall('documents/document'):
    d={}
    d[n.tag]=n.text
    for k,v in n.attrib.items():
        d[k]=v
    L.append(d)
pd.DataFrame(L)

,document,KEY,web
0,"Nevertheless, high and based on experience, fl...",e95a9a6c790ecb95e46cf15bee517651,www.ubm/doc004.com
1,As long as the production is not conducted on ...,bc360cfbafc39970587547215162f0db,www.ubm/doc006.com
2,"Many companies today, in different fields of o...",19e71144c50a8b9160b3f0955e906fce,www.ubm/doc005.com
3,A famous example of a successful prediction is...,21d4af9021a174f61b884606c74d9e42,www.ubm/doc002.com
4,A more recent example of the same kind is the ...,28a45eb2460899763d709ca00ddbb665,www.ubm/doc001.com

#### Otro Ejemplo

In [15]:
archivo='IFC-Subscriptions-and-Voting-Power-of-Member-Count.xml'
file=ET.parse(os.path.join(ruta, archivo))
root=file.getroot()

for nodo in root:
    for snodo in nodo:
        print(snodo.tag,snodo.attrib,snodo.text)
        for ssnodo in snodo:
            print(ssnodo.tag,ssnodo.attrib,ssnodo.text)

row {'_id': 'row-y44j~at3a-b2ir', '_uuid': '00000000-0000-0000-0100-063657E78388', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-y44j~at3a-b2ir'}

member {} Afghanistan
amount_thousands_of_usd {} 1727
percent_of_total_amount {} 0.01
number_of_votes {} 8326
percent_of_total_votes {} 0.04
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-cgqt~xxg3~xehh', '_uuid': '00000000-0000-0000-028B-9164C4785E6F', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-cgqt~xxg3~xehh'}

member {} Albania
amount_thousands_of_usd {} 9927
percent_of_total_amount {} 0.05
number_of_votes {} 16526
percent_of_total_votes {} 0.08
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-q7xr_qk5p_hqh3', '_uuid': '00000000-0000-0000-E37B-CAECEC3A0C26', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-q7xr_qk5p_hqh3'}

member {} Algeria
amount_thousands_of_usd {} 51116
percent_of_total_amount {} 0.25
number_of_votes {} 57715
percent_of_total_votes {} 0.26
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-u2xu-enky.kggg', '_uuid': '00000000-0000-0000-5E03-D3BA6F640E74', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-u2xu-enky.kggg'}

member {} Angola
amount_thousands_of_usd {} 11292
percent_of_total_amount {} 0.05
number_of_votes {} 17891
percent_of_total_votes {} 0.08
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-j7ts~ti34_3pcy', '_uuid': '00000000-0000-0000-2FA7-DDD7B7C43943', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-j7ts~ti34_3pcy'}

member {} Antigua and Barbuda
amount_thousands_of_usd {} 99
percent_of_total_amount {} 0.00
number_of_votes {} 6698
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-geqr.hf5b~pme8', '_uuid': '00000000-0000-0000-7BA7-A38C9799858F', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-geqr.hf5b~pme8'}

member {} Argentina
amount_thousands_of_usd {} 323320
percent_of_total_amount {} 1.56
number_of_votes {} 329919
percent_of_total_votes {} 1.50
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-vct9-gbrd-kdsk', '_uuid': '00000000-0000-0000-6EAF-7A4ED7CD8724', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-vct9-gbrd-kdsk'}

member {} Armenia
amount_thousands_of_usd {} 7564
percent_of_total_amount {} 0.04
number_of_votes {} 14163
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-6tcz.psxe~p4jx', '_uuid': '00000000-0000-0000-F0C9-F90D050B348E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-6tcz.psxe~p4jx'}

member {} Australia
amount_thousands_of_usd {} 401814
percent_of_total_amount {} 1.93
number_of_votes {} 408413
percent_of_total_votes {} 1.86
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-phnu-yhin.6pnb', '_uuid': '00000000-0000-0000-417A-87B21F7C5B8C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-phnu-yhin.6pnb'}

member {} Austria
amount_thousands_of_usd {} 161192
percent_of_total_amount {} 0.78
number_of_votes {} 167791
percent_of_total_votes {} 0.76
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-iysh_uwu8-mbrd', '_uuid': '00000000-0000-0000-1906-7E92EA2CCF37', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-iysh_uwu8-mbrd'}

member {} Azerbaijan
amount_thousands_of_usd {} 18047
percent_of_total_amount {} 0.09
number_of_votes {} 24646
percent_of_total_votes {} 0.11
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-scnb~mk4h~atcb', '_uuid': '00000000-0000-0000-59DE-84BD2BD2B4F1', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-scnb~mk4h~atcb'}

member {} Bahamas, The
amount_thousands_of_usd {} 2554
percent_of_total_amount {} 0.01
number_of_votes {} 9153
percent_of_total_votes {} 0.04
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-eyn7-p3d5_itvt', '_uuid': '00000000-0000-0000-36D6-7172B1E2CB50', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-eyn7-p3d5_itvt'}

member {} Bahrain
amount_thousands_of_usd {} 13313
percent_of_total_amount {} 0.06
number_of_votes {} 19912
percent_of_total_votes {} 0.09
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-5xhz.y8aw~7cxx', '_uuid': '00000000-0000-0000-875E-BF9163FCCF6A', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-5xhz.y8aw~7cxx'}

member {} Bangladesh
amount_thousands_of_usd {} 73440
percent_of_total_amount {} 0.35
number_of_votes {} 80039
percent_of_total_votes {} 0.36
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-n3r2-n8gv.pxn6', '_uuid': '00000000-0000-0000-EF34-D5E63E4E2957', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-n3r2-n8gv.pxn6'}

member {} Barbados
amount_thousands_of_usd {} 2752
percent_of_total_amount {} 0.01
number_of_votes {} 9351
percent_of_total_votes {} 0.04
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-z3fe~yh2x.bb2p', '_uuid': '00000000-0000-0000-E432-4A628F933E8E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-z3fe~yh2x.bb2p'}

member {} Belarus
amount_thousands_of_usd {} 40159
percent_of_total_amount {} 0.19
number_of_votes {} 46758
percent_of_total_votes {} 0.21
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-2mi8-vkvt-tqge', '_uuid': '00000000-0000-0000-0A2F-917771F88F2B', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-2mi8-vkvt-tqge'}

member {} Belgium
amount_thousands_of_usd {} 385880
percent_of_total_amount {} 1.86
number_of_votes {} 392479
percent_of_total_votes {} 1.78
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-wp9x_9cwt-y9zb', '_uuid': '00000000-0000-0000-47BB-629CA09F772C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-wp9x_9cwt-y9zb'}

member {} Belize
amount_thousands_of_usd {} 770
percent_of_total_amount {} 0.00
number_of_votes {} 7369
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-bsru.bbwf-ce4z', '_uuid': '00000000-0000-0000-6248-BB06A9602EDE', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-bsru.bbwf-ce4z'}

member {} Benin
amount_thousands_of_usd {} 907
percent_of_total_amount {} 0.00
number_of_votes {} 7506
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-v26i.tv2s_8daq', '_uuid': '00000000-0000-0000-A8DE-812509DB753E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-v26i.tv2s_8daq'}

member {} Bhutan
amount_thousands_of_usd {} 5490
percent_of_total_amount {} 0.03
number_of_votes {} 12089
percent_of_total_votes {} 0.05
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-d5pv_crx5-fm6f', '_uuid': '00000000-0000-0000-69F9-2DC06374EF0A', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-d5pv_crx5-fm6f'}

member {} Bolivia
amount_thousands_of_usd {} 14502
percent_of_total_amount {} 0.07
number_of_votes {} 21101
percent_of_total_votes {} 0.10
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-ufhx.da26-85rt', '_uuid': '00000000-0000-0000-7C74-E38640986EB9', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-ufhx.da26-85rt'}

member {} Bosnia and Herzegovina
amount_thousands_of_usd {} 5921
percent_of_total_amount {} 0.03
number_of_votes {} 12520
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-zgfu.kw8d.8vwb', '_uuid': '00000000-0000-0000-55E7-0776E0377EF5', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-zgfu.kw8d.8vwb'}

member {} Botswana
amount_thousands_of_usd {} 862
percent_of_total_amount {} 0.00
number_of_votes {} 7461
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-73fr~axud.mhv8', '_uuid': '00000000-0000-0000-AD45-ABDD1076201E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-73fr~axud.mhv8'}

member {} Brazil
amount_thousands_of_usd {} 423812
percent_of_total_amount {} 2.04
number_of_votes {} 430411
percent_of_total_votes {} 1.96
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-4ymb-7kxa_sj6r', '_uuid': '00000000-0000-0000-7B78-0C506B6CC088', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-4ymb-7kxa_sj6r'}

member {} Bulgaria
amount_thousands_of_usd {} 37620
percent_of_total_amount {} 0.18
number_of_votes {} 44219
percent_of_total_votes {} 0.20
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-hpiq.kk3z_uk8d', '_uuid': '00000000-0000-0000-1DFF-B1E7BC4A0A1D', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-hpiq.kk3z_uk8d'}

member {} Burkina Faso
amount_thousands_of_usd {} 6374
percent_of_total_amount {} 0.03
number_of_votes {} 12973
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-zkk3-ftyx_gura', '_uuid': '00000000-0000-0000-E564-806375DE2E2C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-zkk3-ftyx_gura'}

member {} Burundi
amount_thousands_of_usd {} 762
percent_of_total_amount {} 0.00
number_of_votes {} 7361
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-xsde-q2r3~psrk', '_uuid': '00000000-0000-0000-F129-A2A9F6F5A1D3', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-xsde-q2r3~psrk'}

member {} CABO VERDE
amount_thousands_of_usd {} 114
percent_of_total_amount {} 0.00
number_of_votes {} 6713
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-stm5-kuzv-vi7a', '_uuid': '00000000-0000-0000-4219-18A62E093D4D', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-stm5-kuzv-vi7a'}

member {} Cambodia
amount_thousands_of_usd {} 2585
percent_of_total_amount {} 0.01
number_of_votes {} 9184
percent_of_total_votes {} 0.04
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-ycht.7a4c-4ke5', '_uuid': '00000000-0000-0000-A362-2992318BAB44', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-ycht.7a4c-4ke5'}

member {} Cameroon
amount_thousands_of_usd {} 6748
percent_of_total_amount {} 0.03
number_of_votes {} 13347
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-xgga.szsn-b94e', '_uuid': '00000000-0000-0000-D9BB-F2EC2DD11E0E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-xgga.szsn-b94e'}

member {} Canada
amount_thousands_of_usd {} 620199
percent_of_total_amount {} 2.99
number_of_votes {} 626798
percent_of_total_votes {} 2.85
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-tpu8~fvfm-x5id', '_uuid': '00000000-0000-0000-89F0-6B7E8D3717DA', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-tpu8~fvfm-x5id'}

member {} Central African Republic
amount_thousands_of_usd {} 907
percent_of_total_amount {} 0.00
number_of_votes {} 7506
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-2b2v.4hsh-7tsp', '_uuid': '00000000-0000-0000-0271-ADE02734B662', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-2b2v.4hsh-7tsp'}

member {} Chad
amount_thousands_of_usd {} 10400
percent_of_total_amount {} 0.05
number_of_votes {} 16999
percent_of_total_votes {} 0.08
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-2v3b~ybi4_7ew2', '_uuid': '00000000-0000-0000-E241-E6B829A3A2DC', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-2v3b~ybi4_7ew2'}

member {} Chile
amount_thousands_of_usd {} 96428
percent_of_total_amount {} 0.46
number_of_votes {} 103027
percent_of_total_votes {} 0.47
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-c6bi~ct9y.9c4d', '_uuid': '00000000-0000-0000-873A-6B18AA78F685', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-c6bi~ct9y.9c4d'}

member {} China
amount_thousands_of_usd {} 470864
percent_of_total_amount {} 2.27
number_of_votes {} 477463
percent_of_total_votes {} 2.17
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-mkxt.iw8x-m6ip', '_uuid': '00000000-0000-0000-6558-5D0623BE5649', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-mkxt.iw8x-m6ip'}

member {} Colombia
amount_thousands_of_usd {} 104137
percent_of_total_amount {} 0.50
number_of_votes {} 110736
percent_of_total_votes {} 0.50
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-ddiz_pfz8_kvdr', '_uuid': '00000000-0000-0000-773D-D0AB05484411', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-ddiz_pfz8_kvdr'}

member {} Comoros
amount_thousands_of_usd {} 107
percent_of_total_amount {} 0.00
number_of_votes {} 6706
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-p2wp~3f9z.9n4s', '_uuid': '00000000-0000-0000-74D4-0895CBD6404D', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-p2wp~3f9z.9n4s'}

member {} Congo, Democratic Republic of
amount_thousands_of_usd {} 16461
percent_of_total_amount {} 0.08
number_of_votes {} 23060
percent_of_total_votes {} 0.10
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-tg2s.x2v7-xkaz', '_uuid': '00000000-0000-0000-C974-FBED0584B453', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-tg2s.x2v7-xkaz'}

member {} Congo, Republic of
amount_thousands_of_usd {} 999
percent_of_total_amount {} 0.00
number_of_votes {} 7598
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-3bpt-dke2~34t6', '_uuid': '00000000-0000-0000-C865-05C9AC41D473', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-3bpt-dke2~34t6'}

member {} Costa Rica
amount_thousands_of_usd {} 7259
percent_of_total_amount {} 0.03
number_of_votes {} 13858
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-n3p9.7qtq.saxj', '_uuid': '00000000-0000-0000-E4E8-2E7F7C925294', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-n3p9.7qtq.saxj'}

member {} Cote d'Ivoire
amount_thousands_of_usd {} 29443
percent_of_total_amount {} 0.14
number_of_votes {} 36042
percent_of_total_votes {} 0.16
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-wm44-8kgr.7wkm', '_uuid': '00000000-0000-0000-7F42-D8273C36CB7B', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-wm44-8kgr.7wkm'}

member {} Croatia
amount_thousands_of_usd {} 23384
percent_of_total_amount {} 0.11
number_of_votes {} 29983
percent_of_total_votes {} 0.14
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-m6x4.kdiw.69zs', '_uuid': '00000000-0000-0000-2957-4028107E2241', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-m6x4.kdiw.69zs'}

member {} Cyprus
amount_thousands_of_usd {} 16309
percent_of_total_amount {} 0.08
number_of_votes {} 22908
percent_of_total_votes {} 0.10
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-f6g7_7p38-dybb', '_uuid': '00000000-0000-0000-4D7E-CA71479B6D36', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-f6g7_7p38-dybb'}

member {} Czech Republic
amount_thousands_of_usd {} 79076
percent_of_total_amount {} 0.38
number_of_votes {} 85675
percent_of_total_votes {} 0.39
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-u2ng~t3mx_tnu8', '_uuid': '00000000-0000-0000-ABCC-34980FD6D807', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-u2ng~t3mx_tnu8'}

member {} Denmark
amount_thousands_of_usd {} 170267
percent_of_total_amount {} 0.82
number_of_votes {} 176866
percent_of_total_votes {} 0.80
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-kyyk_gxde.jq9b', '_uuid': '00000000-0000-0000-E2EB-2DDF316C2B08', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-kyyk_gxde.jq9b'}

member {} Djibouti
amount_thousands_of_usd {} 160
percent_of_total_amount {} 0.00
number_of_votes {} 6759
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-gz3e.hnc2.ymxw', '_uuid': '00000000-0000-0000-1288-F3C5A6A68C1C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-gz3e.hnc2.ymxw'}

member {} Dominica
amount_thousands_of_usd {} 320
percent_of_total_amount {} 0.00
number_of_votes {} 6919
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-79zk.2amz~vmfd', '_uuid': '00000000-0000-0000-3057-0E32AE875166', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-79zk.2amz~vmfd'}

member {} Dominican Republic
amount_thousands_of_usd {} 9050
percent_of_total_amount {} 0.04
number_of_votes {} 15649
percent_of_total_votes {} 0.07
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-63k4.qbpc-6gbp', '_uuid': '00000000-0000-0000-4AE8-074983F41E18', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-63k4.qbpc-6gbp'}

member {} Ecuador
amount_thousands_of_usd {} 16477
percent_of_total_amount {} 0.08
number_of_votes {} 23076
percent_of_total_votes {} 0.10
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-9izi.fybb-gmxz', '_uuid': '00000000-0000-0000-7A24-32F1458F6D78', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-9izi.fybb-gmxz'}

member {} Egypt, Arab Republic of
amount_thousands_of_usd {} 102017
percent_of_total_amount {} 0.49
number_of_votes {} 108616
percent_of_total_votes {} 0.49
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-rxn5_w92m~pdhf', '_uuid': '00000000-0000-0000-F246-3CF940C3ABD8', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-rxn5_w92m~pdhf'}

member {} El Salvador
amount_thousands_of_usd {} 221
percent_of_total_amount {} 0.00
number_of_votes {} 6820
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-pjuk-v9s8.y8vv', '_uuid': '00000000-0000-0000-8A7D-1F2E86537DE4', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-pjuk-v9s8.y8vv'}

member {} Equatorial Guinea
amount_thousands_of_usd {} 328
percent_of_total_amount {} 0.00
number_of_votes {} 6927
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-7rsr.82wk-dvyy', '_uuid': '00000000-0000-0000-2A52-A234F7812BAD', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-7rsr.82wk-dvyy'}

member {} Eritrea
amount_thousands_of_usd {} 7129
percent_of_total_amount {} 0.03
number_of_votes {} 13728
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-wbxk_k9g8_nvnn', '_uuid': '00000000-0000-0000-2CE7-1C9C19802E2D', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-wbxk_k9g8_nvnn'}

member {} Estonia
amount_thousands_of_usd {} 10934
percent_of_total_amount {} 0.05
number_of_votes {} 17533
percent_of_total_votes {} 0.08
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-7uis_mfuf~dznq', '_uuid': '00000000-0000-0000-F627-4E10E2962C1C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-7uis_mfuf~dznq'}

member {} ESWATINI
amount_thousands_of_usd {} 5215
percent_of_total_amount {} 0.03
number_of_votes {} 11814
percent_of_total_votes {} 0.05
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-qasr.4kha.btve', '_uuid': '00000000-0000-0000-DB1A-00E7458ED3D6', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-qasr.4kha.btve'}

member {} Ethiopia
amount_thousands_of_usd {} 968
percent_of_total_amount {} 0.00
number_of_votes {} 7567
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00

In [16]:
# Lista para almacenar los datos
datos = []

# Iterar sobre cada fila en el XML 
# root.iter("row")  suele ser una forma más directa de recorrer todos los elementos <row> descendientes.
for row in root.findall(".//row"):
    datos_fila = {
        '_id': row.attrib.get('_id', ''),
        '_uuid': row.attrib.get('_uuid', ''),
        '_position': row.attrib.get('_position', ''),
        '_address': row.attrib.get('_address', ''),
        'member': row.findtext("member", ''),
        'amount_thousands_of_usd': row.findtext("amount_thousands_of_usd", ''),
        'percent_of_total_amount': row.findtext("percent_of_total_amount", ''),
        'number_of_votes': row.findtext("number_of_votes", ''),
        'percent_of_total_votes': row.findtext("percent_of_total_votes", ''),
        'as_of_date': row.findtext("as_of_date", '')
    }
    datos.append(datos_fila)

# Crear DataFrame
df = pd.DataFrame(datos)
df

,_id,_uuid,_position,_address,member,amount_thousands_of_usd,percent_of_total_amount,number_of_votes,percent_of_total_votes,as_of_date
0,,,,,,,,,,
1,row-y44j~at3a-b2ir,00000000-0000-0000-0100-063657E78388,0,https://finances.worldbank.org/resource/gsdw-a...,Afghanistan,1727,0.01,8326,0.04,2021-08-06T00:00:00
2,row-cgqt~xxg3~xehh,00000000-0000-0000-028B-9164C4785E6F,0,https://finances.worldbank.org/resource/gsdw-a...,Albania,9927,0.05,16526,0.08,2021-08-06T00:00:00
3,row-q7xr_qk5p_hqh3,00000000-0000-0000-E37B-CAECEC3A0C26,0,https://finances.worldbank.org/resource/gsdw-a...,Algeria,51116,0.25,57715,0.26,2021-08-06T00:00:00
4,row-u2xu-enky.kggg,00000000-0000-0000-5E03-D3BA6F640E74,0,https://finances.worldbank.org/resource/gsdw-a...,Angola,11292,0.05,17891,0.08,2021-08-06T00:00:00
...,...,...,...,...,...,...,...,...,...,...
181,row-qrgm-r2gc-vmf5,00000000-0000-0000-6B23-1E7100931F81,0,https://finances.worldbank.org/resource/gsdw-a...,"Venezuela, Republica Bolivariana de",210347,1.01,216946,0.99,2021-08-06T00:00:00
182,row-v949_etve.z4iu,00000000-0000-0000-D24E-335270F95588,0,https://finances.worldbank.org/resource/gsdw-a...,Vietnam,3401,0.02,10000,0.05,2021-08-06T00:00:00
183,row-44vq_uwjv-izcc,00000000-0000-0000-2518-4C1118CD0F83,0,https://finances.worldbank.org/resource/gsdw-a...,"Yemen, Republic of",5452,0.03,12051,0.05,2021-08-06T00:00:00
184,row-pc34.25ft~32ca,00000000-0000-0000-A697-BD6CF2EAF622,0,https://finances.worldbank.org/resource/gsdw-a...,Zambia,9805,0.05,16404,0.07,2021-08-06T00:00:00
185,row-7dy3~4bef.3bfi,00000000-0000-0000-CD0C-FD2EA362B90B,0,https://finances.worldbank.org/resource/gsdw-a...,Zimbabwe,24513,0.12,31112,0.14,2021-08-06T00:00:00

#### El atajo moderno: `pd.read_xml`

Cuando el XML tiene una estructura regular (un nodo repetido por fila), `pd.read_xml` construye el `DataFrame` en **una sola línea**, detectando etiquetas hijas y atributos automáticamente. Hace lo mismo que el bucle anterior, pero sin escribirlo. (Requiere el paquete `lxml`.)

In [17]:
# pd.read_xml hace en una línea lo que arriba hicimos a mano
pd.read_xml(ruta + '/tabla_1.xml')

            name  rank  year   gdppc
0  Liechtenstein     1  2008  141100
1      Singapore     4  2011   59900
2         Panama    68  2011   13600

#### Buscar en profundidad con `iter` y leer atributos

En árboles más profundos, `iter('tag')` encuentra **todos** los descendientes con esa etiqueta sin importar su nivel. En `tabla_2.xml` cada `<document>` guarda su texto en una sección `CDATA` y sus metadatos (clave, URL) en **atributos**.

In [18]:
# Extraer cada documento con su clave, URL y un fragmento del texto
arbol2 = ET.parse(ruta + '/tabla_2.xml')
raiz2 = arbol2.getroot()

docs = []
for doc in raiz2.iter('document'):
    texto = (doc.text or '').strip()
    docs.append({
        'key': doc.attrib.get('KEY'),
        'web': doc.attrib.get('web'),
        'fragmento': texto[:50] + '...'
    })

df_docs = pd.DataFrame(docs)
df_docs

,key,web,fragmento
0,e95a9a6c790ecb95e46cf15bee517651,www.ubm/doc004.com,"Nevertheless, high and based on experience, fl..."
1,bc360cfbafc39970587547215162f0db,www.ubm/doc006.com,As long as the production is not conducted on ...
2,19e71144c50a8b9160b3f0955e906fce,www.ubm/doc005.com,"Many companies today, in different fields of o..."
3,21d4af9021a174f61b884606c74d9e42,www.ubm/doc002.com,A famous example of a successful prediction is...
4,28a45eb2460899763d709ca00ddbb665,www.ubm/doc001.com,A more recent example of the same kind is the ...

In [19]:
# Los atributos también son datos: metadatos del autor (nodo raíz)
print('Atributos del autor :', raiz2.attrib)
print('Documentos encontrados:', len(list(raiz2.iter('document'))))

Atributos del autor : {'type': '001', 'language': 'EN', 'gender': 'h', 'feature': '00', 'web': '001_00.com'}
Documentos encontrados: 5

## Practica de Laboratorio: Extracción de Archivos XML

Utiliza el archivo `Data/plant_catalog.xml` para construir un pequeño catálogo de plantas en formato tabular (DataFrame). El XML contiene una colección de elementos `PLANT` y, dentro de cada uno, las etiquetas `COMMON`, `BOTANICAL`, `ZONE`, `LIGHT`, `PRICE` y `AVAILABILITY`. Extrae la información del XML, transformarla en un `DataFrame` y realiza consultas de interés, al final exporta el resultado a un archivo CSV.

#### Conteste las siguiente Preguntas

1. ¿Cuántas plantas contiene el catálogo?
2. ¿Cuántas plantas hay en cada zona?
3. ¿Qué tipo de iluminación aparece con mayor frecuencia?
4. ¿Qué nombre científico se repite más veces?

In [20]:
import xml.etree.ElementTree as ET

In [21]:
ruta

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Ingeniería y Ciencia de Datos\\Laboratorio_de_Procesamiento_de_Datos_02026\\Modulo I\\Data'

In [22]:
# 1. Lee el archivo utilizando `xml.etree.ElementTree`.
plantas = ET.parse(ruta + '/plant_catalog.xml')

In [23]:
# 2. Identifica el elemento raíz y cuenta cuántas plantas contiene.
raiz = plantas.getroot()
raiz

In [24]:
# 3. Recorre cada elemento `PLANT` y extrae sus etiquetas.
for nodo in raiz:
    for snodo in nodo:
        print(snodo.tag,snodo.attrib,snodo.text)
        for ssnodo in snodo:
            print(ssnodo.tag,ssnodo.attrib,ssnodo.text)

COMMON {} Bloodroot
BOTANICAL {} Sanguinaria canadensis
ZONE {} 4
LIGHT {} Mostly Shady
PRICE {} $2.44
AVAILABILITY {} 031599
COMMON {} Columbine
BOTANICAL {} Aquilegia canadensis
ZONE {} 3
LIGHT {} Mostly Shady
PRICE {} $9.37
AVAILABILITY {} 030699
COMMON {} Marsh Marigold
BOTANICAL {} Caltha palustris
ZONE {} 4
LIGHT {} Mostly Sunny
PRICE {} $6.81
AVAILABILITY {} 051799
COMMON {} Cowslip
BOTANICAL {} Caltha palustris
ZONE {} 4
LIGHT {} Mostly Shady
PRICE {} $9.90
AVAILABILITY {} 030699
COMMON {} Dutchman's-Breeches
BOTANICAL {} Dicentra cucullaria
ZONE {} 3
LIGHT {} Mostly Shady
PRICE {} $6.44
AVAILABILITY {} 012099
COMMON {} Ginger, Wild
BOTANICAL {} Asarum canadense
ZONE {} 3
LIGHT {} Mostly Shady
PRICE {} $9.03
AVAILABILITY {} 041899
COMMON {} Hepatica
BOTANICAL {} Hepatica americana
ZONE {} 4
LIGHT {} Mostly Shady
PRICE {} $4.45
AVAILABILITY {} 012699
COMMON {} Liverleaf
BOTANICAL {} Hepatica americana
ZONE {} 4
LIGHT {} Mostly Shady
PRICE {} $3.99
AVAILABILITY {} 010299
COMMON {} Jack-In-The-Pulpit
BOTANICAL {} Arisaema triphyllum
ZONE {} 4
LIGHT {} Mostly Shady
PRICE {} $3.23
AVAILABILITY {} 020199
COMMON {} Mayapple
BOTANICAL {} Podophyllum peltatum
ZONE {} 3
LIGHT {} Mostly Shady
PRICE {} $2.98
AVAILABILITY {} 060599
COMMON {} Phlox, Woodland
BOTANICAL {} Phlox divaricata
ZONE {} 3
LIGHT {} Sun or Shade
PRICE {} $2.80
AVAILABILITY {} 012299
COMMON {} Phlox, Blue
BOTANICAL {} Phlox divaricata
ZONE {} 3
LIGHT {} Sun or Shade
PRICE {} $5.59
AVAILABILITY {} 021699
COMMON {} Spring-Beauty
BOTANICAL {} Claytonia Virginica
ZONE {} 7
LIGHT {} Mostly Shady
PRICE {} $6.59
AVAILABILITY {} 020199
COMMON {} Trillium
BOTANICAL {} Trillium grandiflorum
ZONE {} 5
LIGHT {} Sun or Shade
PRICE {} $3.90
AVAILABILITY {} 042999
COMMON {} Wake Robin
BOTANICAL {} Trillium grandiflorum
ZONE {} 5
LIGHT {} Sun or Shade
PRICE {} $3.20
AVAILABILITY {} 022199
COMMON {} Violet, Dog-Tooth
BOTANICAL {} Erythronium americanum
ZONE {} 4
LIGHT {} Shade
PRICE {} $9.04
AVAILABILITY {} 020199
COMMON {} Trout Lily
BOTANICAL {} Erythronium americanum
ZONE {} 4
LIGHT {} Shade
PRICE {} $6.94
AVAILABILITY {} 032499
COMMON {} Adder's-Tongue
BOTANICAL {} Erythronium americanum
ZONE {} 4
LIGHT {} Shade
PRICE {} $9.58
AVAILABILITY {} 041399
COMMON {} Anemone
BOTANICAL {} Anemone blanda
ZONE {} 6
LIGHT {} Mostly Shady
PRICE {} $8.86
AVAILABILITY {} 122698
COMMON {} Grecian Windflower
BOTANICAL {} Anemone blanda
ZONE {} 6
LIGHT {} Mostly Shady
PRICE {} $9.16
AVAILABILITY {} 071099
COMMON {} Bee Balm
BOTANICAL {} Monarda didyma
ZONE {} 4
LIGHT {} Shade
PRICE {} $4.59
AVAILABILITY {} 050399
COMMON {} Bergamot
BOTANICAL {} Monarda didyma
ZONE {} 4
LIGHT {} Shade
PRICE {} $7.16
AVAILABILITY {} 042799
COMMON {} Black-Eyed Susan
BOTANICAL {} Rudbeckia hirta
ZONE {} Annual
LIGHT {} Sunny
PRICE {} $9.80
AVAILABILITY {} 061899
COMMON {} Buttercup
BOTANICAL {} Ranunculus
ZONE {} 4
LIGHT {} Shade
PRICE {} $2.57
AVAILABILITY {} 061099
COMMON {} Crowfoot
BOTANICAL {} Ranunculus
ZONE {} 4
LIGHT {} Shade
PRICE {} $9.34
AVAILABILITY {} 040399
COMMON {} Butterfly Weed
BOTANICAL {} Asclepias tuberosa
ZONE {} Annual
LIGHT {} Sunny
PRICE {} $2.78
AVAILABILITY {} 063099
COMMON {} Cinquefoil
BOTANICAL {} Potentilla
ZONE {} Annual
LIGHT {} Shade
PRICE {} $7.06
AVAILABILITY {} 052599
COMMON {} Primrose
BOTANICAL {} Oenothera
ZONE {} 3 - 5
LIGHT {} Sunny
PRICE {} $6.56
AVAILABILITY {} 013099
COMMON {} Gentian
BOTANICAL {} Gentiana
ZONE {} 4
LIGHT {} Sun or Shade
PRICE {} $7.81
AVAILABILITY {} 051899
COMMON {} Blue Gentian
BOTANICAL {} Gentiana
ZONE {} 4
LIGHT {} Sun or Shade
PRICE {} $8.56
AVAILABILITY {} 050299
COMMON {} Jacob's Ladder
BOTANICAL {} Polemonium caeruleum
ZONE {} Annual
LIGHT {} Shade
PRICE {} $9.26
AVAILABILITY {} 022199
COMMON {} Greek Valerian
BOTANICAL {} Polemonium caeruleum
ZONE {} Annual
LIGHT {} Shade
PRICE {} $4.36
AVAILABILITY {} 071499
COMMON {} California Poppy
BOTANICAL {} Eschscholzia californica
ZONE {} Annual
LIGHT {} Sun
PRICE {} $7.89
AVAILABILITY {} 032799
COMMON {} Shooting Star
BOTANICAL {} Dodecatheon
ZONE {} Annual
LIGHT {} Mostly Shady
PRICE {} $8.60
AVAILABILITY {} 051399
COMMON {} Snakeroot
BOTANICAL {} Cimicifuga
ZONE {} Annual
LIGHT {} Shade
PRICE {} $5.63
AVAILABILITY {} 071199
COMMON {} Cardinal Flower
BOTANICAL {} Lobelia cardinalis
ZONE {} 2
LIGHT {} Shade
PRICE {} $3.02
AVAILABILITY {} 022299

In [25]:
# 4. Construye un `DataFrame` con las columnas: `nombre_comun`,`nombre_cientifico`,`zona`,`luz`,`precio`,`disponibilidad`
registros =[]
for planta in raiz.findall('PLANT'):
    registros.append({
        'nombre_comun': planta.findtext('COMMON'),
        'nombre_cientifico': planta.findtext('BOTANICAL'),
        'Zona': planta.findtext('ZONE'),
        'luz': planta.findtext('LIGHT'),
        'Precio': planta.findtext('PRICE'),
        'disponibilidad': planta.findtext('AVAILABILITY'),
    })
df_plantas = pd.DataFrame(registros)
df_plantas

,nombre_comun,nombre_cientifico,Zona,luz,Precio,disponibilidad
0,Bloodroot,Sanguinaria canadensis,4,Mostly Shady,$2.44,031599
1,Columbine,Aquilegia canadensis,3,Mostly Shady,$9.37,030699
2,Marsh Marigold,Caltha palustris,4,Mostly Sunny,$6.81,051799
3,Cowslip,Caltha palustris,4,Mostly Shady,$9.90,030699
4,Dutchman's-Breeches,Dicentra cucullaria,3,Mostly Shady,$6.44,012099
5,"Ginger, Wild",Asarum canadense,3,Mostly Shady,$9.03,041899
6,Hepatica,Hepatica americana,4,Mostly Shady,$4.45,012699
7,Liverleaf,Hepatica americana,4,Mostly Shady,$3.99,010299
8,Jack-In-The-Pulpit,Arisaema triphyllum,4,Mostly Shady,$3.23,020199
9,Mayapple,Podophyllum peltatum,3,Mostly Shady,$2.98,060599
10,"Phlox, Woodland",Phlox divaricata,3,Sun or Shade,$2.80,012299
11,"Phlox, Blue",Phlox divaricata,3,Sun or Shade,$5.59,021699
12,Spring-Beauty,Claytonia Virginica,7,Mostly Shady,$6.59,020199
13,Trillium,Trillium grandiflorum,5,Sun or Shade,$3.90,042999
14,Wake Robin,Trillium grandiflorum,5,Sun or Shade,$3.20,022199
15,"Violet, Dog-Tooth",Erythronium americanum,4,Shade,$9.04,020199
16,Trout Lily,Erythronium americanum,4,Shade,$6.94,032499
17,Adder's-Tongue,Erythronium americanum,4,Shade,$9.58,041399
18,Anemone,Anemone blanda,6,Mostly Shady,$8.86,122698
19,Grecian Windflower,Anemone blanda,6,Mostly Shady,$9.16,071099
20,Bee Balm,Monarda didyma,4,Shade,$4.59,050399
21,Bergamot,Monarda didyma,4,Shade,$7.16,042799
22,Black-Eyed Susan,Rudbeckia hirta,Annual,Sunny,$9.80,061899
23,Buttercup,Ranunculus,4,Shade,$2.57,061099
24,Crowfoot,Ranunculus,4,Shade,$9.34,040399
25,Butterfly Weed,Asclepias tuberosa,Annual,Sunny,$2.78,063099
26,Cinquefoil,Potentilla,Annual,Shade,$7.06,052599
27,Primrose,Oenothera,3 - 5,Sunny,$6.56,013099
28,Gentian,Gentiana,4,Sun or Shade,$7.81,051899
29,Blue Gentian,Gentiana,4,Sun or Shade,$8.56,050299
30,Jacob's Ladder,Polemonium caeruleum,Annual,Shade,$9.26,022199
31,Greek Valerian,Polemonium caeruleum,Annual,Shade,$4.36,071499
32,California Poppy,Eschscholzia californica,Annual,Sun,$7.89,032799
33,Shooting Star,Dodecatheon,Annual,Mostly Shady,$8.60,051399
34,Snakeroot,Cimicifuga,Annual,Shade,$5.63,071199
35,Cardinal Flower,Lobelia cardinalis,2,Shade,$3.02,022299

In [26]:
df_plantas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nombre_comun       36 non-null     object
 1   nombre_cientifico  36 non-null     object
 2   Zona               36 non-null     object
 3   luz                36 non-null     object
 4   Precio             36 non-null     object
 5   disponibilidad     36 non-null     object
dtypes: object(6)
memory usage: 1.8+ KB

In [27]:
# 5. Exporta el resultado a `Data/plant_catalog.csv`.
df_plantas.to_csv(ruta + '/plant_catalog.csv')

In [ ]:
# 6. Lee nuevamente el CSV con `pd.read_csv()` y verifica que conserve el mismo número de registros.